echo "================= RAILWAY REMOTE DOCTOR ==============="
echo ""
echo "👉 PROCESS LIST"
ps aux | grep node || echo "no node processes running"
echo ""
echo "👉 DIST FOLDER"
ls -R /app/dist 2>/dev/null || echo "❌ dist folder missing"
echo ""
echo "👉 ENVIRONMENT VARIABLES"
printenv | sort
echo ""
echo "👉 PORTS LISTENING"
netstat -tulnp 2>/dev/null || ss -tulnp 2>/dev/null || echo "no netstat or ss available"
echo ""
echo "========================================================"
echo "   END OF REMOTE REPORT"
echo "========================================================"
