/**
 * Diagnostic Engines Registry (A8 SAFE MODE)
 * ------------------------------------------
 * This file is regenerated by A8. It only wires SAFE engines:
 *  - Existing engines with no suspect external/network tokens
 *  - SAFE stubs created by A8
 *
 * Do NOT manually introduce network calls here.
 */

import signalNormalizer from "./signalNormalizer.js";
import blindSpotDetector from "./blindSpotDetector.js";
import driftDetector from "./driftDetector.js";
import errorClassificationEngine from "./errorClassificationEngine.js";
import signalWeightOptimizer from "./signalWeightOptimizer.js";

export const DIAGNOSTIC_ENGINES = [
  signalNormalizer,
  blindSpotDetector,
  driftDetector,
  errorClassificationEngine,
  signalWeightOptimizer
];

export default DIAGNOSTIC_ENGINES;
