import fmpService from './fmpService.js';

interface FlowSignal {
  type: 'ROTATION' | 'ACCUMULATION' | 'DUMPING';
  sector?: string;
  ticker?: string;
  intensity: number; // 0-100
  reason: string;
}

const SECTOR_ETFS = ['XLK', 'XLE', 'XLV', 'XLF', 'XLI', 'XLC', 'XLY', 'XLP', 'XLB', 'XLRE', 'XLU'];

class InstitutionalFlowService {
  
  async scanFlows(): Promise<FlowSignal[]> {
    console.log('   📡 Flow Radar: Scanning Institutional Movements...');
    const signals: FlowSignal[] = [];

    // 1. SECTOR ROTATION (Money moving between sectors)
    try {
        // Fetch quotes for all sector ETFs
        const quotes = await fmpService.getBatchPrices(SECTOR_ETFS);
        const quoteMap = new Map(quotes.map((q: any) => [q.symbol, q]));
        
        // Identify winners and losers
        const sorted = SECTOR_ETFS.map(s => quoteMap.get(s)).filter(q => q).sort((a, b) => b.changePercent - a.changePercent);
        
        if (sorted.length > 1) {
            const winner = sorted[0];
            const loser = sorted[sorted.length - 1];
            
            if (winner.changePercent > 1.0) {
                signals.push({
                    type: 'ROTATION',
                    sector: winner.symbol,
                    intensity: Math.min(100, winner.volume / 10000), // Rough volume score
                    reason: `Institutional Rotation INTO ${winner.symbol} (+${winner.changePercent.toFixed(2)}%).`
                });
                console.log(`      -> Rotation DETECTED: Into ${winner.symbol}`);
            }
        }
    } catch(e) {}

    // 2. STEALTH ACCUMULATION (The Dark Pool Proxy)
    // Logic: High Volume + Low Price Movement = Hidden Buying/Selling
    // We check this on our "Shortlist" generated by other engines later
    
    return signals;
  }

  // Called by Execution Agent to validate a specific ticker
  async checkAccumulation(ticker: string): Promise<FlowSignal | null> {
      try {
          const quote = await fmpService.getPrice(ticker);
          if (!quote) return null;

          // Heuristic: Volume > 1.5x Avg (we approximate avg as volume/1.5 for now or fetch profile)
          // FMP quote includes avgVolume? No, profile does.
          const profile = await fmpService.getCompanyProfile(ticker);
          const avgVol = profile?.volAvg || 1000000;

          const volRatio = quote.volume / avgVol;
          const priceChange = Math.abs(quote.changePercent);

          // High Volume (2x+) but Price stayed Flat (<0.5%)
          if (volRatio > 2.0 && priceChange < 0.5) {
              return {
                  type: 'ACCUMULATION',
                  ticker,
                  intensity: 90,
                  reason: `Stealth Accumulation: Volume ${volRatio.toFixed(1)}x normal, but price flat.`
              };
          }
          
          // High Volume (2x+) and Price Up (>2%) = Breakout
          if (volRatio > 2.0 && quote.changePercent > 2.0) {
               return {
                  type: 'ACCUMULATION',
                  ticker,
                  intensity: 95,
                  reason: `High Volume Breakout: Volume ${volRatio.toFixed(1)}x normal.`
              };
          }
      } catch(e) {}
      return null;
  }
}

export default new InstitutionalFlowService();
