import Anthropic from '@anthropic-ai/sdk';
import { extractJSON } from '../utils/aiUtils.js';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || process.env.CLAUDE_API_KEY
});

interface AuditResult {
  ticker: string;
  original_confidence: number;
  adjusted_confidence: number;
  bias_detected: boolean;
  bias_type: string; // 'Recency', 'Hype', 'Confirmation', 'None'
  correction_note: string;
}

class MetaAnalystService {

  // Audits a batch of hypotheses for cognitive flaws
  async auditTheses(hypotheses: any[]): Promise<AuditResult[]> {
    console.log('      🧠 Meta-Analyst: Auditing for Cognitive Bias...');
    
    if (hypotheses.length === 0) return [];

    const context = hypotheses.map(h =>
      `TICKER: ${h.ticker} | CONFIDENCE: ${h.base_confidence} | THESIS: ${h.thesis} | BULL: ${h.bull_argument} | BEAR: ${h.bear_argument}`
    ).join('\n\n');

    const prompt = `
      ACT AS: Chief Risk Officer (Bias Auditor).
      
      INPUT: A list of trade hypotheses generated by a junior analyst.
      
      TASK: Audit each thesis for Cognitive Biases:
      1. Recency Bias: Overweighting breaking news without context.
      2. Emotional Hype: Using words like "Rocket", "Moon", "Unstoppable".
      3. Confirmation Bias: Weak Bear case compared to Bull case.
      4. Overgeneralization: "AI is booming so buy this random stock."

      ACTION:
      - If bias is found, REDUCE the confidence score (e.g. 90 -> 75).
      - Add a "correction_note" explaining the bias.
      - If clean, keep confidence same.

      DATA TO AUDIT:
      ${context.substring(0, 10000)}

      OUTPUT STRICT JSON ARRAY:
      [
        {
          "ticker": "SYM",
          "original_confidence": 90,
          "adjusted_confidence": 75,
          "bias_detected": true,
          "bias_type": "Recency Bias",
          "correction_note": "Thesis relies entirely on yesterday's news drop."
        }
      ]
    `;

    try {
        const msg = await anthropic.messages.create({
            model: 'claude-3-haiku-20240307',
            max_tokens: 2000,
            messages: [{ role: 'user', content: prompt }]
        });
        
        const text = msg.content[0].type === 'text' ? msg.content[0].text : '[]';
        const results = extractJSON(text);
        
        if (Array.isArray(results)) {
            // Log interventions
            results.forEach(r => {
                if (r.bias_detected) {
                    console.log(`      ⚠️ Bias Detected on ${r.ticker}: ${r.bias_type} (${r.original_confidence} -> ${r.adjusted_confidence})`);
                }
            });
            return results;
        }
        return [];

    } catch (e) {
        console.error("Meta-Analyst Audit Failed:", e);
        return [];
    }
  }
}

export default new MetaAnalystService();
