/**
 * A9 Source Ingestion Registry (SAFE MODE)
 * ----------------------------------------
 * This file is AUTO-GENERATED by autowire_a9.sh.
 * It does NOT import or execute any collectors/services/engines.
 * It is pure metadata, safe to keep under source control.
 *
 * Each entry describes an intended Source → Collector → Service → Engine chain.
 * Status values:
 *   - "WIRED"          : collector + service + engine all exist
 *   - "NO_ENGINE"      : collector + service exist, engine missing
 *   - "COLLECTOR_ONLY" : only collector exists
 *   - "SERVICE_ONLY"   : only service exists
 *   - "NO_COLLECTOR"   : service + engine exist, collector missing
 *   - "BROKEN_CHAIN"   : collector + engine exist, service missing
 *   - "ORPHAN"         : partial or unclear wiring
 *
 * SAFE MODE:
 *   This registry is NOT wired into runtime.
 *   Future steps can selectively consume it for Catalyst Hunter or diagnostics.
 */

export type A9SourceStatus =
  | "WIRED"
  | "NO_ENGINE"
  | "COLLECTOR_ONLY"
  | "SERVICE_ONLY"
  | "NO_COLLECTOR"
  | "BROKEN_CHAIN"
  | "ORPHAN";

export interface A9SourcePipeline {
  id: string;
  label: string;
  domain: string;
  collectorFile: string | null;
  serviceFile: string | null;
  engineFile: string | null;
  status: A9SourceStatus;
}

export const A9_SOURCE_PIPELINES: A9SourcePipeline[] = [
  {
    id: "crypto_pipeline",
    label: "Crypto Intelligence (Collector → Correlation → Engine)",
    domain: "crypto",
    collectorFile: "src/services/collectors/cryptoCollector.ts",
    serviceFile: "src/services/cryptoIntelligenceService.ts",
    engineFile: "src/services/cryptoStockCorrelationService.ts",
    status: "WIRED",
  },
  {
    id: "whale_pipeline",
    label: "Whale & Smart Money Flow",
    domain: "whale",
    collectorFile: "src/services/collectors/whaleCollector.ts",
    serviceFile: "src/services/smartMoneyHeatmapService.ts",
    engineFile: "src/services/whaleContrarianService.ts",
    status: "WIRED",
  },
  {
    id: "macro_pipeline",
    label: "Macro / FRED Economic Series",
    domain: "macro",
    collectorFile: "src/services/collectors/fredCollector.ts",
    serviceFile: "src/services/economicDataService.ts",
    engineFile: null,
    status: "NO_ENGINE",
  },
  {
    id: "insider_pipeline",
    label: "Insider & 13F Institutional Flow",
    domain: "insider",
    collectorFile: "src/services/collectors/insiderCollector.ts",
    serviceFile: "src/services/governmentDataService.ts",
    engineFile: "src/services/hedgeFund13FEngine.ts",
    status: "WIRED",
  },
  {
    id: "geopolitical_pipeline",
    label: "Geopolitics, Executive Orders, Regulation",
    domain: "geopolitics",
    collectorFile: null,
    serviceFile: "src/services/geopoliticalIntelligenceService.ts",
    engineFile: null,
    status: "SERVICE_ONLY",
  },
  {
    id: "social_sentiment_pipeline",
    label: "Social + Reddit Sentiment",
    domain: "sentiment",
    collectorFile: null,
    serviceFile: "src/services/expandedSocialService.ts",
    engineFile: null,
    status: "SERVICE_ONLY",
  },
  {
    id: "iv_microstructure_pipeline",
    label: "Options IV + Microstructure",
    domain: "options",
    collectorFile: null,
    serviceFile: "src/services/ivNavigatorService.ts",
    engineFile: "src/services/microstructureService.ts",
    status: "NO_COLLECTOR",
  },
  {
    id: "retail_explanation_pipeline",
    label: "Retail Interpretability",
    domain: "explainability",
    collectorFile: null,
    serviceFile: "src/services/retailInterpretabilityService.ts",
    engineFile: null,
    status: "SERVICE_ONLY",
  },
  {
    id: "market_data_pipeline",
    label: "General Market Data (Stable FMP Wrapper)",
    domain: "core_market",
    collectorFile: null,
    serviceFile: "src/services/marketDataService.ts",
    engineFile: null,
    status: "SERVICE_ONLY",
  }
];
